import {
  Baby,
  Book,
  Briefcase,
  Bus,
  Car,
  Circle,
  Clapperboard,
  Coffee,
  Dumbbell,
  Fuel,
  Gift,
  GraduationCap,
  HeartPulse,
  Home,
  Laptop,
  Music,
  MoreHorizontal,
  PawPrint,
  Percent,
  Pizza,
  Plane,
  Plug,
  Repeat,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Tag,
  TrendingUp,
  Wallet,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  utensils: Coffee,
  "shopping-cart": ShoppingCart,
  home: Home,
  plug: Plug,
  car: Car,
  fuel: Fuel,
  "shopping-bag": ShoppingBag,
  clapperboard: Clapperboard,
  "heart-pulse": HeartPulse,
  "graduation-cap": GraduationCap,
  plane: Plane,
  repeat: Repeat,
  shield: Shield,
  sparkles: Sparkles,
  "more-horizontal": MoreHorizontal,
  wallet: Wallet,
  laptop: Laptop,
  briefcase: Briefcase,
  percent: Percent,
  "trending-up": TrendingUp,
  gift: Gift,
  bus: Bus,
  pizza: Pizza,
  music: Music,
  book: Book,
  dumbbell: Dumbbell,
  baby: Baby,
  "paw-print": PawPrint,
  smartphone: Smartphone,
  stethoscope: Stethoscope,
  wrench: Wrench,
  tag: Tag,
  circle: Circle,
};

export const ICON_PICKER_OPTIONS = Object.keys(ICON_MAP);

export function CategoryIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICON_MAP[name] ?? Circle;
  return <Icon className={className} />;
}
